USE DB;
GO


ALTER TABLE AUDITORIUM ADD CONSTRAINT FK_AUDITORIUM_TYPE FOREIGN KEY (AUDITORIUM_TYPE) REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE);
ALTER TABLE TEACHER ADD CONSTRAINT FK_TEACHER_PULPIT FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT);
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_GROUPS FOREIGN KEY (IDGROUP) REFERENCES GROUPS(IDGROUP);
ALTER TABLE SUBJECT ADD CONSTRAINT FK_SUBJECT_PULPIT FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT);
ALTER TABLE GROUPS ADD CONSTRAINT FK_GROUPS_FACULTY FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY);
ALTER TABLE PROFESSION ADD CONSTRAINT FK_PROFESSION_FACULTY FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY);
ALTER TABLE PROGRESS ADD CONSTRAINT FK_PROGRESS_STUDENT FOREIGN KEY (IDSTUDENT) REFERENCES STUDENT(IDSTUDENT);
ALTER TABLE PROGRESS ADD CONSTRAINT FK_PROGRESS_SUBJECT FOREIGN KEY (SUBJECT) REFERENCES SUBJECT(SUBJECT);
GO



ALTER TABLE TEACHER ADD BDATE DATE NOT NULL DEFAULT '19600101';
GO

ALTER TABLE TEACHER ALTER COLUMN TEACHER_NAME VARCHAR(50) NOT NULL;
GO



INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES ('ИТ', 'Информационных технологий');
INSERT INTO PROFESSION (PROFESSION, FACULTY, PROFESSION_NAME, QUALIFICATION) VALUES ('ПОИТ', 'ИТ', 'Программное обеспечение инфотехнологий', 'Инженер-программист');
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY) VALUES ('ИСиТ', 'Информационных систем и технологий', 'ИТ');
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, GENDER, PULPIT, BDATE) VALUES ('АКНВЧ', 'Акунович Станислав Иванович', 'м', 'ИСиТ', '1965-05-12');
INSERT INTO GROUPS (IDGROUP, FACULTY, PROFESSION, YEAR_FIRST, COURSE) VALUES (1, 'ИТ', 'ПОИТ', 2024, 1);

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPE_NAME) VALUES ('ЛК', 'Лекционная'), ('ЛБ-К', 'Лаборатория компьютерная'), ('ХХХХ', 'Специальная');
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME) VALUES ('101-4', 'ЛК', 90.000, '101-4'), ('102-4', 'ЛК', 60.000, '102-4'), ('205-4', 'ЛБ-К', 25.000, '205-4'), ('301-1', 'ЛБ-К', 30.000, '301-1'), ('400-4', 'ХХХХ', 15.000, '400-4');
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT) VALUES ('БД', 'Базы данных', 'ИСиТ'), ('КГ', 'Компьютерная графика', 'ИСиТ'), ('ООП', 'Объектно-ориентированное программирование', 'ИСиТ');

INSERT INTO STUDENT (IDSTUDENT, IDGROUP, PULPIT, NAME) VALUES (101, 1, 'ИСиТ', 'Иванов Иван Иванович'), (102, 1, 'ИСиТ', 'Petrov Петр Петрович'), (103, 1, 'ИСиТ', 'Сидорова Анна Сергеевна');
GO

EXEC SP_HELP TEACHER;
GO

SELECT *, LEN(TEACHER_NAME) AS 'len(TEACHER_NAME)' FROM TEACHER ORDER BY TEACHER;
GO

DECLARE @y1 numeric(8,3) = (SELECT CAST(SUM(AUDITORIUM_CAPACITY) AS numeric(8,3)) FROM AUDITORIUM), @y2 numeric(8,3), @y3 numeric(8,3), @y4 numeric(8,3);
IF @y1 > 200
BEGIN
    PRINT 'Общее количество мест больше 200'
    SELECT @y2 = CAST((SELECT COUNT(*) FROM AUDITORIUM) AS numeric(8,3)), @y3 = (SELECT CAST(AVG(AUDITORIUM_CAPACITY) AS numeric(8,3)) FROM AUDITORIUM);
    SET @y4 = (SELECT CAST(COUNT(*) AS numeric(8,3)) FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY > @y3);
    SELECT @y1 AS '@y1', @y2 AS '@y2', @y3 AS '@y3', @y4 AS '@y4', @y4/@y2*100 AS '%';
END
ELSE
    PRINT 'Общее количество мест меньше или равно 200';
GO

DECLARE @StudentsCount int = (SELECT COUNT(*) FROM STUDENT), @AuditoriumCount int = (SELECT COUNT(*) FROM AUDITORIUM), @TeacherCount int = (SELECT COUNT(*) FROM TEACHER);
SELECT AUDITORIUM_TYPE AS [Тип аудитории], COUNT(*) AS [Количество аудиторий] FROM AUDITORIUM GROUP BY AUDITORIUM_TYPE;
SELECT PULPIT AS [Кафедра], COUNT(*) AS [Количество дисциплин] FROM SUBJECT GROUP BY PULPIT;
PRINT 'Количество студентов        : ' + CAST(@StudentsCount AS varchar(10));
PRINT 'Количество аудиторий        : ' + CAST(@AuditoriumCount AS varchar(10));
PRINT 'Количество преподавателей   : ' + CAST(@TeacherCount AS varchar(10));
GO
